x-veld:
  chain:
    about:
      description: "dummy veld for testing and showcasing"

services:
  veld_fetch:
    extends:
      file: ./veld_dummy_executable_1_fetch_json/veld.yaml
      service: veld
    volumes:
      - ./tmp/data.json:/veld/output/a/data.json
      - ./tmp/log_fetch.txt:/veld/output/b/log.txt

  veld_convert:
    extends:
      file: ./veld_dummy_executable_2_json_to_xml/veld.yaml
      service: veld
    volumes:
      - ./tmp/data.json:/veld/input/data.json
      - ./tmp/data.xml:/veld/output/data.xml
    depends_on:
      veld_fetch:
        condition: service_completed_successfully

  veld_validate:
    extends:
      file: ./veld_dummy_executable_3_validate_xml/veld.yaml
      service: veld
    volumes:
      - ./tmp/data.xml:/veld/input/a/data.xml
      - ./tmp/validation_result.txt:/veld/output/result.txt
    depends_on:
      veld_convert:
        condition: service_completed_successfully

  veld_db:
    extends:
      file: ./veld_dummy_executable_4_existdb/veld.yaml
      service: veld
    volumes:
      - ./veld_dummy_data_3_existdb/data:/exist/data
    networks:
      - existdb
    depends_on:
      veld_convert:
        condition: service_completed_successfully

  veld:
    image: curlimages/curl:8.2.1 
    command: curl -s -f -T /data.xml --user admin:"" veld_db:8080/exist/rest/db/data.xml
    volumes:
      - ./tmp/data.xml:/data.xml
    networks:
      - existdb
    depends_on:
      veld_db:
        condition: service_healthy

networks:
  existdb:
